import os
import csv
from datetime import datetime

from tasks.celery_app import celery
from tasks.reminder_tasks import get_flask_app


@celery.task
def generate_monthly_report():

    app = get_flask_app()

    with app.app_context():

        from models.student import Student
        from models.company import Company
        from models.drive import Drive
        from models.application import Application
        from models.user import User
        from services.email_service import send_email

        report = {
            "Generated On": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "Total Students": Student.query.count(),
            "Total Companies": Company.query.count(),
            "Total Drives": Drive.query.count(),
            "Approved Drives": Drive.query.filter_by(status="approved").count(),
            "Closed Drives": Drive.query.filter_by(status="closed").count(),
            "Applications": Application.query.count(),
            "Selected": Application.query.filter_by(status="selected").count(),
            "Rejected": Application.query.filter_by(status="rejected").count(),
            "Shortlisted": Application.query.filter_by(status="shortlisted").count(),
            "Applied": Application.query.filter_by(status="applied").count(),
        }

        # -----------------------------
        # CSV Generation
        # -----------------------------

        reports_folder = os.path.join(
            app.root_path,
            "reports"
        )

        os.makedirs(
            reports_folder,
            exist_ok=True
        )

        filename = (
            f"placement_report_"
            f"{datetime.now().strftime('%Y_%m_%d_%H_%M_%S')}.csv"
        )

        filepath = os.path.join(
            reports_folder,
            filename
        )

        with open(
            filepath,
            "w",
            newline="",
            encoding="utf-8"
        ) as csvfile:

            writer = csv.writer(csvfile)

            writer.writerow(["Metric", "Value"])

            for key, value in report.items():
                writer.writerow([key, value])

        # -----------------------------
        # HTML Report
        # -----------------------------

        html = f"""
        <html>

        <body style="font-family:Arial">

        <h2>Monthly Placement Activity Report</h2>

        <table
            border="1"
            cellpadding="8"
            cellspacing="0"
        >

        <tr>

            <th>Metric</th>

            <th>Value</th>

        </tr>

        {''.join(
            f"<tr><td>{k}</td><td>{v}</td></tr>"
            for k,v in report.items()
        )}

        </table>

        <br>

        <p>

        This report was automatically generated by the
        Placement Portal.

        </p>

        </body>

        </html>
        """

        # -----------------------------
        # Send Email
        # -----------------------------

        admin = User.query.filter_by(
            role="admin"
        ).first()

        if admin:

            send_email(

                subject="Monthly Placement Activity Report",

                recipients=[admin.email],

                html=html

            )

            print(
                f"Monthly report emailed to {admin.email}"
            )

        print("=" * 60)
        print("MONTHLY REPORT GENERATED")
        print(filepath)
        print("=" * 60)

        return filepath